### ISSUE TITLE
Github actions 打包支持

### ISSUE THREAD

**Issue by petronny** [archlinuxcn/lilac#149]
archlinuxcn/repo#1575

FAQ:
1. 必要性何在
我觉得带有run_cmd的lilac.*其实都是不安全的，万一来一个`rm -rf ~`虽说不会搞炸系统但是也很恶心的，所以扔个docker里跑可能也挺好的
剩下的就是透明度啥的

1. 和现有的lilac是什么关系
我打算把这个作为一个特殊的build_prefix交给lilac，即整体还是由lilac决定打哪些包和时序上的依赖关系
然后每个pkgbase都做一个专门的workflow，lilac通过发送一个内容为对应pkgbase的POST请求触发workflow
结束时一个artifact到这个workflow run，然后lilac下载这个artifact就可以和原来的lilac兼容

1. 可否使用devtools
可以

1. 依赖关系如何解决
首先前置依赖的包的artifact是60天有效。
然后对于一个有依赖的包，先查找依赖包的artifact还在不在，在的话直接下载这个；
如果artifact不在了，说明肯定超过60天了，mirror里肯定有，从合适的mirror下载即可。

1. 缓存如何解决
github actions有缓存，不过只有5G大小。
建议是做一个叫pacman-cache-x86_64的缓存只用来缓存extra-x86_64-build下载的包。
repo_depends、source等的只能下载了

1. 性能问题如何解决
虽然单个包的确慢，但结合 #145 的话，20个包并行打还是很好的。
对于某些特别吃资源的包，可以不用这个，还在本地打包。
后期的话希望lilac也由一个专门的workflow来运行，高性能服务器做一个self-hosted action runner

1. 有无预览
我给无依赖的yay做了一个，可以参考 https://github.com/petronny/arch4edu/blob/master/.github/workflows/yay.yml
一个对应的运行实例在
https://github.com/petronny/arch4edu/actions/runs/113176984
打包结果和log在
https://github.com/petronny/arch4edu/suites/710761537/artifacts/6924885
https://github.com/petronny/arch4edu/suites/710761537/artifacts/6924884

1. 目前还有何问题
    1. 自动下载依赖包没做了
我可以做一个python版本的，就是递归读一下yml，然后用github token/mirror下载
但最好是通过js实现并封装
    1. workflow配置文件巨长
调查了一下可以通过自定义action的做法封装一些固定操作
我写了一个预览版（就是假设actions都封装好了），见最后
应该和原来的lilac.*差不多了
    1. actions如何封装？
查了一下custom actions分为docker和js版两种。
我们应该是要用js版的，就是在js里调用各种shell命令，下载文件什么的
可以参考 https://github.com/actions/checkout ，
这个就是通过git命令clone一个repo到当前目录，后面的steps可以读。
所以文件IO，命令执行什么的应该都是可行的。
不过有个问题是我js基本不会。。。所以需要帮助了。。。

----
```
name: yay

on:
  repository_dispatch:
    types: [yay]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux
      options: --privileged
      volumes:
        - /sys/fs/cgroup:/sys/fs/cgroup

    steps:
      - name: Initialize build environment
        uses: archlinuxcn/lilac/actions/initialize-extra-x86_64@master

      - uses: actions/checkout@master

      - uses: archlinuxcn/lilac/actions/aur-pre-build@master

      - name: Build package
        id: build
        uses: archlinuxcn/lilac/actions/extra-x86_64-build@master
        with:
          exclude_package: yay-test yay-test2
          repo_depends: a b/b
          archbuild_args:
          makechrootpkg_args:
          makepkg_args:

      - uses: archlinuxcn/lilac/actions/aur-post-build@master

      - uses: archlinuxcn/lilac/actions/post-process@master
```
