### ISSUE TITLE
giving options to use a custom pacman.conf

### ISSUE THREAD

**Issue by moodyhunter** [archlinuxcn/lilac#191]
firstly, thanks for the great project :)

when building packages for the `testing` repo, e.g. tracking packages versions from the testing repository:

```
# following testing/gdb version
update_on:
  - source: alpm
    alpm: gdb
    repo: testing
```

However, this seems impossible without adding `[testing]` entries into my own `/etc/pacman.conf`

(Of course one doesn't want to do so, even appending `testing` at the end of the file makes me feel it nasty)

I'd suggest adding an option for providing one's custom `pacman.conf`.

PS: I know packages in `testing` will be removed as soon as they are stabilized, but this issue does apply to other cases: "package for repo X when one doesn't want X to be configured on the build machine"
